### ISSUE TITLE
[16.0]iot_oca : Communication system not available for creation

### ISSUE THREAD

**Issue by flotho** [OCA/iot#89]
Hi everyone,

Im' wondering why it is forbidden to create manually communication system : https://github.com/OCA/iot/blob/16.0/iot_oca/views/iot_system_views.xml#L7
@olgamarcocb  @etobella  any reason to document  ?
thanks for the answer

**Comment by etobella** [comment]
Because you need to add some code to make it work

**Comment by mostafabarmshory** [comment]
In the other word, Communication System itself is an abstract entity. For example, we may have an HTTP communication system or even MQTT. So you have to install other modules to have a real one.

**Comment by flotho** [comment]
Thanks to all of you, 
I think that this repo could get massive attraction if more documentation could be provided (https://github.com/OCA/iot/pull/88#issuecomment-1608975704)
As an example, I love the way @guewen explain how to use is awesome module https://github.com/OCA/queue/tree/16.0/queue_job

**Comment by mostafabarmshory** [comment]
Bro, I`m busy with migration. Let me finish it, then I can add more documents.

**Comment by flotho** [comment]
for sure @mostafabarmshory , no pressure from me, just playing the review game ;-) not judging
