### ISSUE TITLE
Input method with a complex parameter.

### ISSUE THREAD

**Issue by mostafabarmshory** [OCA/iot#90]
I have a device that sends many data at a time. For example, it sends x, y, and z related to an employee id. So the value itself is a dict with many entries.

If the input action accepts JSON request, then we can pass a complex value such as a dict.

The current implementation accepts FORM data.

In the other case, we could call an input action with many parameters.

**Comment by mostafabarmshory** [comment]
@etobella
I find a way to support parameters as JSON (key, vals). How can I add it to the branch 16.0?

My main need is to connect ThingsBoard MQTT queue to odoo. And TB supports JSON in its rule chain. So, JSON parameter is a good choice for me.

My new approach supports both, form and JSON request body.

It may be useful for others too.

**Comment by etobella** [comment]
Sure! Make a PR and I will review it
